name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ['main']

jobs:
  build:

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check coding standards
        if: matrix.node-version == '21.x' && matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Static analysis - check types
        if: matrix.node-version == '21.x' && matrix.os == 'ubuntu-latest'
        run: npm run ts
      - name: Test
        run: npm run coverage
      - uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
